export const projects = [
    {
        title: 'Auto Seller Platform',
        type: 'Full-Stack',
        year: 2026,
        featured: true,
        detailsEnabled: true,
        slug: 'rv-auto-seller',
        desc: 'Secure full-stack car marketplace similar to OLX, focused on vehicle listings. Users can browse and filter cars, view listing details, contact sellers, leave reviews, and schedule viewing appointments. Built with a Spring Boot REST API secured with JWT authentication, PostgreSQL persistence, and a Vue frontend integrated via Axios.',
        tech: ['Java','Spring Boot','Spring Security','JWT','REST API','PostgreSQL','Spring Data JPA (Hibernate)','Bean Validation','Lombok','Vue.js','Vite','Vue Router','Axios'],
        tags: ['Full-Stack','Marketplace','Auth/JWT','REST','PostgreSQL','Appointments','Reviews'],
        github: 'https://github.com/palroland21/RV-AUTO-SELLER',
    },
    {
        title: 'Instagram Clone',
        type: 'Full-Stack',
        year: 2026,
        featured: true,
        detailsEnabled: false,
        desc: 'Full-stack social media clone inspired by Instagram. Users can register/login, manage profiles, upload images, create/edit/delete posts, like/dislike posts, comment, use tags, and receive notifications. Includes a separate admin microservice for user/content moderation and an automated CI pipeline for building and validating the project. Built with Spring Boot REST APIs, JWT security, PostgreSQL, Cloudinary, and a React frontend.',
        tech: ['Java','Spring Boot','Spring Security','JWT','REST API','PostgreSQL','Spring Data JPA (Hibernate)','Cloudinary','React','Axios','Admin Microservice','CI Pipeline'],
        tags: ['Full-Stack','Social Media','Auth/JWT','REST','PostgreSQL','Cloudinary','Admin Panel','Notifications','CI/CD'],
        github: 'https://github.com/palroland21/Instagram-Clone',
    },
    {
        title: 'ResQ - AI Insurance Platform (PoliHack)',
        type: ['Full-Stack', 'AI'],
        year: 2025,
        featured: true,
        detailsEnabled: false,
        desc: 'Crisis response PWA built in 48 hours: Victims create help requests and Rescuers can browse, filter, and accept nearby cases. Includes GPS-based map view (Leaflet), role-based auth, AI medical triage with Gemini (severity 1–3), and Stripe payments for donations/subscriptions.',
        tech: ['Java 17','Spring Boot','Spring Security','JWT','PostgreSQL','JPA/Hibernate','Vue 3','Google Maps','Vite','Pinia','Leaflet (Maps/GPS)','Stripe','Gemini AI','Firebase'],
        tags: ['AI Triage','Maps/GPS','Auth/JWT','Stripe Payments','Hackathon','APIs','Web','PWA'],
        github: 'https://github.com/palroland21/PoliHack',
    },
    {
        title: 'Pascal VOC Semantic Segmentation',
        type: ['AI', 'Deep Learning'],
        year: 2026,
        featured: true,
        detailsEnabled: false,
        desc: 'Deep learning computer vision project for semantic segmentation on Pascal VOC 2012. Trains and evaluates a DeepLabV3 model with a ResNet-50 backbone, uses preprocessing and data augmentation, fine-tunes pretrained weights, and adds an auxiliary multi-label classification head for image-level object presence prediction. Compares baseline, fine-tuned, and multi-task models using pixel accuracy, mean IoU, classification accuracy, and micro F1-score.',
        tech: ['Python','PyTorch','Torchvision','DeepLabV3','ResNet-50','Semantic Segmentation','Transfer Learning','Fine-tuning','Multi-task Learning','NumPy','Pandas','Matplotlib','Pillow','Jupyter Notebook'],
        tags: ['AI','Deep Learning','Computer Vision','Semantic Segmentation','PyTorch','Transfer Learning','Fine-tuning','mIoU'],
        github: 'https://github.com/palroland21/Pascal_VOC_Dataset-Deep_Learning',
    },
    {
        title: 'Titanic Dataset - Machine Learning',
        type: ['AI', 'Machine Learning'],
        year: 2026,
        featured: true,
        detailsEnabled: false,
        desc: 'Machine learning project on the Titanic dataset focused on binary classification: predicting passenger survival. Includes exploratory data analysis, missing value handling, feature preprocessing with encoding and scaling, train/test splitting, model training, and model comparison. Evaluates Logistic Regression, Decision Tree, Random Forest, SVM with RBF kernel, and Random Forest with GridSearchCV using accuracy, precision, recall, and confusion matrices.',
        tech: ['Python','Jupyter Notebook','Pandas','NumPy','Matplotlib','Scikit-learn','Logistic Regression','Decision Tree','Random Forest','SVM','GridSearchCV','EDA','Preprocessing'],
        tags: ['AI','Machine Learning','Classification','EDA','Scikit-learn','SVM','Random Forest','GridSearchCV'],
        github: 'https://github.com/palroland21/Titanic-Dataset---Machine-Learning',
    },
    {
        title: 'Traffic Sign Detection - OpenCV',
        type: 'OpenCV',
        year: 2026,
        featured: true,
        detailsEnabled: false,
        desc: 'Classical computer vision project for detecting and recognizing traffic signs from images. Uses HSV color segmentation for red, blue, and yellow regions, Gaussian filtering, morphological operations, contour extraction, candidate filtering, geometric shape analysis, and rule-based validation to identify signs such as STOP, Yield, Priority Road, Pedestrian Crossing, Mandatory Ahead, No Entry, One Way, and No Stopping.',
        tech: ['C++','OpenCV','Visual Studio','Image Processing','HSV Color Segmentation','Gaussian Blur','Morphological Operations','Contour Extraction','Shape Analysis','Rule-Based Classification'],
        tags: ['OpenCV','Computer Vision','Image Processing','C++','HSV','Contours','Morphology','Traffic Signs'],
        github: 'https://github.com/palroland21/Traffic-Sign-Detection-OpenCV',
    },
    {
        title: 'Queue Management Simulation',
        type: 'Systems',
        year: 2024,
        featured: false,
        detailsEnabled: false,
        desc: 'Multithreaded queue simulation with a Swing UI for configuring the scenario (clients, queues, simulation time, arrival/service ranges). Generates random clients and dispatches them to servers using scheduling strategies (shortest queue / shortest waiting time), while logging the real-time evolution and computing final stats like average waiting/service time and peak hour.',
        tech: ['Java','OOP','Multithreading','Swing','BlockingQueue','Synchronization','Atomic/Locks','File Logging'],
        tags: ['Concurrency','Scheduling','Simulation','GUI','OOP','Desktop'],
        github: 'https://github.com/palroland21/Queue-Management-Application-in-JAVA',
    },
    {
        title: 'FPGA Memory Game (Nexys A7) + UART Logger',
        type: 'FPGA',
        year: 2026,
        featured: true,
        detailsEnabled: false,
        desc: 'FPGA memory game in VHDL on Nexys4/Nexys A7 with a clear Game FSM (generate → show → input → check → win/lose). Uses a 16-bit LFSR for pseudo-random digit sequences (0–9), Pmod KYPD 4x4 keypad input with edge-detect, and a multiplexed 7-seg driver where the display speed increases with level. After each round, the board sends level + result over UART to a Python (pyserial) logger that adds timestamps and tracks best score.',
        tech: ['VHDL','Vivado','Nexys A7 (Artix-7)','FSM Design','LFSR (16-bit)','7-Segment Multiplexing','Pmod KYPD (4x4)','UART TX','Python','pyserial'],
        tags: ['FPGA','VHDL','Digital Design','UART','Verification'],
        github: 'https://github.com/palroland21/VHDL-JocDeMemorie--FPGA-Python',
    },
    {
        title: 'Horror First-Person Game (OpenGL)',
        type: 'OpenGL',
        year: 2026,
        featured: true,
        detailsEnabled: false,
        desc: 'First-person horror exploration scene in an abandoned hospital, built in OpenGL with FPS camera (WASD + mouse), door interaction (animated open/close + auto-close), collisions (AABB + player cylinder), gravity with multi-level floor patches, camera flashlight spotlight with shadow mapping (depth pass + PCF), plus distance-based monster audio for atmosphere.',
        tech: ['C++','OpenGL','GLSL','GLFW','GLM','Shadow Mapping','PCF','Collision System (AABB + Cylinder)','miniaudio','stb_image','tinyobjloader','OBJ/MTL Pipeline'],
        tags: ['GameDev','OpenGL','Shaders','Shadow Mapping','Physics','Audio'],
        github: 'https://github.com/palroland21/Horror-First-Person-Camera-Game',
    },
    {
        title: 'AI Search Agent (Pacman)',
        type: 'AI',
        year: 2026,
        featured: false,
        detailsEnabled: false,
        desc: 'Search algorithms for the UC Berkeley Pacman AI project. Implemented DFS/BFS/UCS/A* plus advanced problems like CornersProblem and FoodSearchProblem with admissible heuristics (Manhattan-based) and heuristic caching for faster runs. Includes a greedy ClosestDotSearchAgent and passes the autograder with max score.',
        tech: ['Python 3','State-Space Search','DFS','BFS','Uniform Cost Search','A* Search','Admissible Heuristics','Manhattan Distance','Maze Distance','Heuristic Caching (problem.heuristicInfo)','Pacman AI Framework (UC Berkeley)','Autograder'],
        tags: ['AI','Search','A*','UCS','Heuristics','Pacman'],
        github: 'https://github.com/palroland21/AI-Search-Agent-Pacman',
    },
    {
        title: 'AI Multi-Agent Search (Pacman)',
        type: 'AI',
        year: 2026,
        featured: true,
        detailsEnabled: false,
        desc: 'Adversarial multi-agent decision-making for the UC Berkeley Pacman AI project. Implemented a ReflexAgent plus Minimax and Alpha-Beta pruning agents that model Pacman (MAX) vs. Ghosts (MIN), look ahead over game trees, and choose actions using evaluation functions while handling terminal states (win/lose) and depth control.',
        tech: ['Python 3','Adversarial Search','Minimax','Alpha-Beta Pruning','Game Trees','Heuristic Evaluation','Pacman AI Framework (UC Berkeley)','Autograder'],
        tags: ['AI','Game AI','Adversarial Search','Minimax','Alpha-Beta','Heuristics'],
        github: 'https://github.com/palroland21/AI-Multi-Agent-Seach',
    },
    {
        title: 'AI Reinforcement Learning (Pacman)',
        type: 'AI',
        year: 2026,
        featured: true,
        detailsEnabled: false,
        desc: 'Reinforcement Learning agents for the UC Berkeley Pacman project. Implemented MDP planning with Value Iteration (including Prioritized Sweeping), plus model-free Q-Learning with epsilon-greedy exploration and Approximate Q-Learning using feature extractors. Tested in Gridworld and Pacman, with parameter analysis for different optimal policies.',
        tech: ['Python 3','MDP','Value Iteration','Prioritized Sweeping','Q-Learning','Approximate Q-Learning','Epsilon-Greedy','Feature Extractors','Gridworld','Pacman AI Framework (UC Berkeley)','Autograder'],
        tags: ['AI','Reinforcement Learning','MDP','Q-Learning','Planning','Pacman'],
        github: 'https://github.com/palroland21/AI-Reinforcement-Learning',
    },
    {
        title: 'Dozator de Cola (VHDL) – Coin-Operated Dispenser',
        type: 'FPGA',
        year: 2023,
        featured: false,
        detailsEnabled: false,
        desc: 'Digital vending machine implemented in VHDL: accepts 5/10/50 bani coins via photodetector inputs (F0–F2), rejects invalid coins/foreign objects (F3), accumulates credit using an 8-bit adder, and releases Coca-Cola when the user presses the dispense button. If credit is insufficient, it signals “FonduriInsuficiente” and returns coins; if credit exceeds 100 bani, it also triggers change return. Designed as a black-box then split into Control Unit (UC) and Execution Unit (UE) for clean control vs datapath separation.',
        tech: ['VHDL','Digital Design','FSM Control Logic','Control Unit (UC) / Execution Unit (UE)','MUX 4:1','8-bit Adder (Full Adders)','Clocked Logic','I/O Interface (Photocells + Button)'],
        tags: ['FPGA','VHDL','Digital Design','FSM','Datapath'],
        github: 'https://github.com/palroland21/PROIECT-Dozator-De-Cola',
    },
    {
        title: 'MIPS Processor (VHDL) – Single-Cycle + Pipeline',
        type: 'FPGA',
        year: 2024,
        featured: true,
        detailsEnabled: false,
        desc: 'Designed and simulated two MIPS CPU architectures in VHDL: a complete single-cycle processor (ALU, register file, instruction/data memory, control signals) and an extended 5-stage pipelined version (IF, ID, EX, MEM, WB) using pipeline registers. Added hazard handling via forwarding and hazard detection, and validated execution flow with dedicated testbenches for arithmetic, branching, and memory instructions.',
        tech: ['VHDL','CPU Architecture','MIPS ISA','Single-Cycle Datapath','5-Stage Pipeline (IF/ID/EX/MEM/WB)','Pipeline Registers','Hazard Detection Unit','Forwarding Unit','Control Unit','ALU','Register File','Testbenches','Simulation/Timing Verification'],
        tags: ['FPGA','CPU Design','MIPS','Pipeline','Hazards','VHDL','Digital Design'],
        github: 'https://github.com/palroland21/MIPS',
    },
    {
        title: 'BallEscape (Java Game)',
        type: 'Systems',
        year: 2023,
        featured: false,
        detailsEnabled: false,
        desc: 'Small Java arcade-style game where the player controls a ball and must avoid obstacles to survive and score points. Built as a lightweight desktop project focused on game loop logic, collision checks, and simple UI rendering.',
        tech: ['Java','OOP','2D Game Loop','Collision Detection','Desktop UI'],
        tags: ['Java','GameDev','Desktop','OOP'],
        github: 'https://github.com/palroland21/JavaGame_BallEscape',
    },
    {
        title: 'Anti-Theft System (ESP32)',
        type: 'Embedded',
        year: 2024,
        featured: false,
        detailsEnabled: false,
        desc: 'Motion-based anti-theft system for a bicycle built on ESP32. Uses a GY-521 (MPU6050 accelerometer/gyroscope) over I2C to detect movement above calibrated thresholds. The alarm is armed/disarmed from the phone via Arduino IoT Remote, and when motion is detected it triggers a visual alert (2 red LEDs blinking) and an audible alert (active buzzer). A green LED indicates the system is powered/active.',
        tech: ['ESP32','Arduino (C/C++)','MPU6050 / GY-521','I2C (Wire.h)','Arduino IoT Cloud / Arduino IoT Remote','Threshold Calibration','LED + Buzzer Output','Serial Debugging'],
        tags: ['Embedded','ESP32','Sensors','I2C','Alarm','IoT'],
        github: 'https://github.com/palroland21/Anti-theft_system-Arduino',
    },
    {
        title: 'Database Project (PHP + MySQL) – Stored Procedures & Queries',
        type: 'PHP',
        year: 2024,
        featured: false,
        detailsEnabled: false,
        desc: 'Web mini-app in PHP that authenticates users (login + session) and exposes a set of database exercises as interactive queries. Uses prepared statements and calls multiple MySQL stored procedures (CALL ...) to fetch results such as tests by semester/date, correct answers for a given test, fully answered tests, per-test question count and total score, and question ranking based on a computed ratio.',
        tech: ['PHP','HTML','MySQL','Stored Procedures','Prepared Statements','Sessions/Auth','SQL Queries'],
        tags: ['Database','SQL','Stored Procedures','PHP','Web'],
        github: 'https://github.com/palroland21/Database-Project-with-PHP',
    },
]